version : '3.5'

services:
  angular-service:
    container_name: corona-UI-container
    build: ./
    volumes:
    - './:/usr/src/app'
    ports:
      - "4200:4200"
    command: >
      bash -c "npm start"